FROM eclipse-temurin:25-jre

WORKDIR /work/

COPY target/quarkus-app/ ./

EXPOSE 8080 27777

VOLUME ["/work/conf", "/work/logs", "/work/data"]

# The "-Dquarkus.http.host=0.0.0.0" argument is important to make the application accessible from outside the container.
CMD ["java", "-Dquarkus.http.host=0.0.0.0", "-jar", "quarkus-run.jar"]
