%test.smsg.routing.file.path=src/test/resources/routingTable.conf
%test.smsg.properties.file.path=src/test/resources/smsg.properties
%test.smsg.credentials.file.path=src/test/resources/credentials.yml