name: Build Docker Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*' # Specify the Node.js version you use
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend Application
        working-directory: ./frontend
        run: npm run build

      - name: Move Frontend Assets to Backend
        run: |
          cp -r frontend/dist/* sms-gateway/src/main/resources/META-INF/resources/

      - name: Setup Java
        id: setup_java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'

      - name: Build Backend Application
        working-directory: ./sms-gateway
        run: ./mvnw -B package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./sms-gateway
          file: ./sms-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sendium:latest