name: 🤖 Automatic Issue Labeler
on:
  - pull_request_target

jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add labels based on content
        uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}